version: '3.8'
services:
  fastapi:
    build: .
    command: uvicorn FastApi:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - streamlit

  streamlit:
    build: .
    command: streamlit run StreamlitMain.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"